### PR TITLE
Update dependencies and fix resulting errors.

### PR DESCRIPTION
**Pull request by john-codeworx**
My IDE appears to have made some changes by adding some brackets to equations as well...  otherwise this fixes some audit warnings from ```npm audit```.

### CODE REVIEW

**Comment by john-codeworx** [comment]
Fixed first issues with tests failing by upgrading jest.  However I'm getting errors where the buffers don't match.  Tried running tests in upstream/master which failed on a different error.  Could these be addressed?  This may then lead to the buffer no equaling errors that I'm getting...

**Comment by jamescryer** [comment]
Sorry for the late reply.  

The new diff images are slightly different, so the buffers are different.  The images the tests compare against need to regenerated. Easily done using `fs.writeFileSync(`./path/file.png`,buffer);` during a test run.

Unfortunately the update means that comparison results are now a little different than before which may cause problems for some users.  For this reason this is going to have to be a major release, in which case I'm inclined to wait until canvas-prebuilt is in beta.  Once the PR is passing CI I'll create a branch for the v3 release.

**Comment by j0tunn** [comment]
@jamescryer what about this PR? 
`canvas-prebuilt@1.6.x` has a bug in its `install` script which was fixed in 2.x
This bug leads to `npm instal` fails when there are some other packages with `node-pre-gyp` in their dependencies.

**Comment by j0tunn** [comment]
@jamescryer In fact there is no need in `canvas-prebuilt` module anymore. Since version 2 `canvas` downloads prebuilt modules by itself: https://github.com/Automattic/node-canvas/blob/v2.0.1/package.json#L32
See https://github.com/node-gfx/node-canvas-prebuilt/issues/60#issuecomment-432734973 for details
Can you publish new version of `resemblejs` now?

**Comment by j0tunn** [comment]
@john-codeworx can you update your PR to use `canvas` instead of `canvas-prebuilt`?

**Comment by jamescryer** [comment]
Latest version now uses Canvas 2

**Pull request closed without merging**
